sudo: required
language: minimal
services:
- docker
addons:
  apt:
    packages:
    - docker-ce
before_install: 
script:
- sh build.sh
after_success:
  - if [ -z $DOCKER_NS ] ; then
      export DOCKER_NS=openfaas;
      fi
  - if [ ! -z "$TRAVIS_TAG" ] ; then
      export DOCKER_CLI_EXPERIMENTAL=enabled

      docker tag $DOCKER_NS/of-watchdog:latest-dev-darwin $DOCKER_NS/of-watchdog:$TRAVIS_TAG-darwin;
      docker tag $DOCKER_NS/of-watchdog:latest-dev-armhf $DOCKER_NS/of-watchdog:$TRAVIS_TAG-armhf;
      docker tag $DOCKER_NS/of-watchdog:latest-dev-arm64 $DOCKER_NS/of-watchdog:$TRAVIS_TAG-arm64;
      docker tag $DOCKER_NS/of-watchdog:latest-dev-windows $DOCKER_NS/of-watchdog:$TRAVIS_TAG-windows;
      docker tag $DOCKER_NS/of-watchdog:latest-dev-x86_64 $DOCKER_NS/of-watchdog:$TRAVIS_TAG-x86_64;
      echo $DOCKER_PASSWORD | docker login -u=$DOCKER_USERNAME --password-stdin;
      docker push $DOCKER_NS/of-watchdog:$TRAVIS_TAG-darwin;
      docker push $DOCKER_NS/of-watchdog:$TRAVIS_TAG-armhf;
      docker push $DOCKER_NS/of-watchdog:$TRAVIS_TAG-arm64;
      docker push $DOCKER_NS/of-watchdog:$TRAVIS_TAG-windows; 
      docker push $DOCKER_NS/of-watchdog:$TRAVIS_TAG-x86_64;

      ./make_manifest.sh
      docker push $DOCKER_NS/of-watchdog:$TRAVIS_TAG

      echo $QUAY_PASSWORD | docker login -u=$QUAY_USERNAME --password-stdin quay.io;
      docker push quay.io/$DOCKER_NS/of-watchdog:$TRAVIS_TAG-armhf;
      docker push quay.io/$DOCKER_NS/of-watchdog:$TRAVIS_TAG-arm64;
      docker push quay.io/$DOCKER_NS/of-watchdog:$TRAVIS_TAG-windows; 
      docker push quay.io/$DOCKER_NS/of-watchdog:$TRAVIS_TAG-x86_64;
      fi
before_deploy:
  - ./ci/hashgen.sh
deploy:
  provider: releases
  api_key:
    secure: "viDbC8aYSozUuEC6KTZz9oJIcwLqSD/vM0o8WeWnnrdTmJfFnt2meNaco6MWE4OcaJv9teS1nic4VzYY8rMtAWWs9nTEdWytuJiyXYbEzaquAnNlMwZT4szHVyDAHjcnkiFHGhhMqYjnsFpRfk8BzjLG5IrouKh5gyVSRTCsFR8hQeJXE6HlKBUC4uppZ/tghsXt5PeXSQH2zPWEotGpbojdO3CWHI2JXPjzqWYB976hkGUkDOx2p+YklldZ/apjkLWt9KwK9kl02TdtS+IXu1v5itIcg4rs320t50d96eUPAETznh3RPN5g62IRgMTnTA9I5TsHKvYLDgZYdvReF3Wex/qAVwLzYWcV4tf8Gwi7LAZQyixjXGgqY0kKZ594D16zwhJhmqmFtTnSJwsXulEStgsRfzLRiUMybq8M2lCfIHELi1mD2ANqXP8AfkJBu3+ZpYL0fEmH+4M1R+FOxlxvvTFd7Hj72bAPy9ccWCTmBi5SCiAapnpTbIeizMGc23fMrlnK0+aNE+gyIWqLEuqyic/SEoL89mToClxUcjVORTle4pRaEu+3fYRp8h4LVhvrLWeE6tG5xy7Pf2SFaj5EMeYbq6HiDh2gaTh6ZUW1uPn6RTRjMxOsTArq+deTeZWPu5buJz6A4etj8e3TqZbrVz71a+X9fggvKfIeQvs="
  file:
  - "./of-watchdog"
  - "./of-watchdog-armhf"
  - "./of-watchdog-arm64"
  - "./of-watchdog-darwin"
  - "./of-watchdog.exe"
  - "./of-watchdog.sha256"
  - "./of-watchdog-armhf.sha256"
  - "./of-watchdog-arm64.sha256"
  - "./of-watchdog-darwin.sha256"
  - "./of-watchdog.exe.sha256"
  skip_cleanup: true
  on:
    tags: true  
